#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
setenv DACAPOHOME /opt/dacapo
prepend-path PATH /opt/dacapo/bin
prepend-path  PYTHONPATH /opt/dacapo/python/lib/python2.7/site-packages
setenv DACAPOPATH /opt/dacapo/bin/dacapo_run
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )
