NAME               = dacapo_$(ROLLCOMPILER)_$(ROLLMPI)_$(ROLLNETWORK)
VERSION            = 3.8.0
RELEASE            = 1
PKGROOT            = /opt/dacapo

SRC_SUBDIR         = dacapo

SOURCE_NAME        = dacapo
SOURCE_VERSION     = $(VERSION)
SOURCE_SUFFIX      = tar.gz
SOURCE_PKG         = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR         = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

PYTHONASE_NAME     = python-ase
PYTHONASE_VERSION  = 3.8.0.3420
PYTHONASE_PKG      = $(PYTHONASE_NAME)-$(PYTHONASE_VERSION).$(SOURCE_SUFFIX)
PYTHONASE_DIR      = $(PYTHONASE_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS        = $(SOURCE_PKG) $(PYTHONASE_PKG)
RPM.EXTRAS         = AutoReq:No
