#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0

set compiler "nocompiler"
set mpi ""
if {[module-info mode switch1] || [module-info mode switch3]} {
  set commandWords [split [exec /bin/ps -p [pid] -o args=] " "]
  set switchFrom [lindex [split [module-info name] "/"] 0]
  set switchTo [lindex [split [lindex \$commandWords end] "/"] 0]
  set loadApps [expr  [string equal \$switchTo \$switchFrom]]
} elseif {[module-info mode remove]} {
  set loadApps 0
} else {
   set loadApps 1
}
if { \$loadApps  }  {
 if {[info exists env(LOADEDMODULES)]} {
  foreach app [split \$env(LOADEDMODULES) ":"] {
     if { [ string match "*intel*" \$app ] == 1 } {
          set compiler "intel"
     } elseif { [ string match "*pgi*" \$app ] == 1 } {
          set compiler "pgi"
     } elseif { [ string match "*gnu*" \$app ] == 1 && [ string match *gnubase* \$app ] == 0 } {
          set compiler "gnu"
     }
     if { [ string match "*mvapich2*" \$app ] == 1 } {
          set mpi "mvapich2"
     } elseif { [ string match "*openmpi*" \$app ] == 1 } {
          set mpi "openmpi"
     } elseif { [ string match "*mpich2*" \$app ] == 1 } {
          set mpi "mpich2"
     }
  }
 }

 if { [ string equal "nocompiler" \$compiler ] ==  1 } {
      module load ROLLCOMPILER
      module load ROLLMPI_ROLLNETWORK
  } elseif { [ string equal "ROLLCOMPILER" \$compiler ] ==  1 } {
      module unload \${mpi}_ROLLNETWORK
      module load ROLLMPI_ROLLNETWORK
  } else {
      module unload \$compiler
      module load ROLLCOMPILER
      module load ROLLMPI_ROLLNETWORK
  }
}
setenv GROMACSHOME /opt/gromacs
setenv GMXBIN /opt/gromacs/bin
setenv GMXDATA /opt/gromacs/share
setenv GMXLDLIB /opt/gromacs/lib
setenv GMXMAN /opt/gromacs/share/man
prepend-path PATH /opt/gromacs/bin
prepend-path LD_LIBRARY_PATH /opt/gromacs/lib
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )
