#!/bin/bash
/bin/mkdir -m 0755 -p ROOT_PKGROOTMODULEROOT

cat > ROOT_PKGROOTMODULEROOT/VERSION <<END
#%Module1.0
setenv GROMACSHOME /opt/gromacs
setenv GMXBIN /opt/gromacs/bin
setenv GMXDATA /opt/gromacs/share
setenv GMXLDLIB /opt/gromacs/lib
setenv GMXMAN /opt/gromacs/share/man
prepend-path PATH /opt/gromacs/bin
prepend-path LD_LIBRARY_PATH /opt/gromacs/lib
END

chmod 0644  ROOT_PKGROOTMODULEROOT/VERSION

cat > ROOT_PKGROOTMODULEROOT/.version.VERSION <<END
#%Module1.0
set ModulesVersion "VERSION"
END

(cd ROOT_PKGROOTMODULEROOT; if test ! -e .version; then /bin/ln -s .version.VERSION .version; fi )
